spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/property_management
    username: postgres
    password: pg123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
