spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/property_management
    username: sean
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect  
    properties:
      hibernate:
        format_sql: true
