global:
  scrape_interval: 20s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'jmeter'
    scrape_interval: 5s
    static_configs:
      - targets: ['jmeter-host:9270']