name: Dev integration

on:
    pull_request:
        branches: [ dev ]
    
jobs:
    frontend-run:
        uses: ./.github/workflows/frontend.yml

    backend-run:
        uses: ./.github/workflows/backend.yml