name: Frontend CI

on:
    push:
        branches: [frontend]
    pull_request:
        branches: [frontend]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
              working-directory: ./Frontend
            - name: Lint code
              run: npm run lint
              working-directory: ./Frontend
        
    build:
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - uses: actions/checkout@v3
            - name: Build Angular website
              run: npm run build
              working-directory: ./Frontend

