name: Frontend CI

on:
    push:
        branches: [frontend]
    pull_request:
        branches: [frontend]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Cache node_modules
              uses: actions/cache@v3
              with:
                path: Frontend/Property-Manager/node_modules
                key: npm-${{ hashFiles('Frontend/Property-Manager/package-lock.json') }}
                restore-keys: |
                  npm-

            - name: Install dependencies
              run: npm ci
              working-directory: Frontend/Property-Manager

            - name: Lint code
              run: npm run lint
              working-directory: Frontend/Property-Manager
        
    build:
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - uses: actions/checkout@v3

            - name: Cache node_modules
              uses: actions/cache@v3
              with:
                path: Frontend/Property-Manager/node_modules
                key: npm-${{ hashFiles('Frontend/Property-Manager/package-lock.json') }}
                restore-keys: |
                  npm-

            - name: Install dependencies
              run: npm ci
              working-directory: Frontend/Property-Manager

            - name: Build Angular website
              run: npm run build
              working-directory: Frontend/Property-Manager
      
    test:
      runs-on: ubuntu-latest
      needs: build
      steps:
          - uses: actions/checkout@v3

          - name: Cache node_modules
            uses: actions/cache@v3
            with:
                path: Frontend/Property-Manager/node_modules
                key: npm-${{ hashFiles('Frontend/Property-Manager/package-lock.json') }}
                restore-keys: |
                  npm-

          - name: Install dependencies
            run: npm ci
            working-directory: Frontend/Property-Manager

          - name: Run unit tests
            run: npm run test
            working-directory: Frontend/Property-Manager